"""Markdown cleanup helpers for EPFR conversion pipelines."""

import re

_IMAGE_ONLY_LINE_RE = re.compile(r"^\s*!\[[^\]]*\]\([^)]+\)\s*$")


def clean_markdown_text(text: str) -> str:
    """Remove token-heavy markdown artifacts before persisting files.

    Args:
        text: Markdown content generated by document conversion or OCR.

    Returns:
        Cleaned markdown content with redundant artifacts removed.

    """
    cleaned_lines: list[str] = []
    blank_streak = 0

    for raw_line in text.splitlines():
        line = raw_line.rstrip()
        stripped = line.strip()

        if stripped and set(stripped) <= {"|"}:
            continue

        if _IMAGE_ONLY_LINE_RE.match(stripped):
            continue

        if stripped:
            blank_streak = 0
            cleaned_lines.append(line)
            continue

        blank_streak += 1
        if blank_streak <= 1:
            cleaned_lines.append("")

    return "\n".join(cleaned_lines).strip()
