[project]
name = "workflows"
version = "0.0.0"
requires-python = '>=3.14,<3.15'

[project.optional-dependencies]
style = [
    "ruff==0.15.16",
    "ty==0.0.37",
]

[tool.ruff]
src = ["src"]
line-length = 120
target-version = "py314"

[tool.ruff.format]
docstring-code-format = true

[tool.ruff.lint]
select = ["F", "E", "W", "I", "D", "B", "UP", "C4", "SIM", "PIE", "T20"]
ignore = ["E501", "E712"]

[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["F401", "D100"]
"epfr-downloader/src/workflows/start.py" = ["E402"]
"epfr-downloader/src/discover.py" = ["E402"]
"src/migrations/**" = ["E101", "W", "E"]

[tool.ruff.lint.isort]
known-first-party = ["workflows"]
lines-after-imports = 2
lines-between-types = 1
combine-as-imports = true
force-sort-within-sections = true
split-on-trailing-comma = true

[tool.ruff.lint.pydocstyle]
convention = "google"
