[project]
name = "centraldepo-parser"
version = "0.1.0"
description = "A Mistral Workflows project"
requires-python = "==3.14.3"
dependencies = [
    "mistralai-workflows==3.1.1",
    "pydantic==2.13.2",
    "python-dotenv==1.2.2",
    "aiohttp==3.13.5",
    "python-docx==1.2.0",
    "docx2txt==0.9",
    "xlrd==2.0.2",
    "mistralai-workflows-plugins-mistralai==3.1.1",
    "mistralai==2.4.0",
    "beautifulsoup4==4.14.3",
    "lxml==6.1.0",
]

[dependency-groups]
dev = [
    "ruff==0.15.11",
    "mypy==1.20.1",
    "pytest==9.0.3",
]
